services:
    web:
        build: .
        image: lms-demo
        ports:
            - "8080:8088"
        environment:
            - PYTHONUNBUFFERED=1
            - xPG_INIT_DB=postgresql://postgres:abc123@db/postgres
            - xLMS_ADMIN_DB=postgresql://lmsadmin:very-secret-123@db/lmsdemo
            - xINIT_DB_PASSWORD=zyx987
            - LMS_PROD_DB=postgresql://lmsserver:secret123@db/lmsdemo
            - YENOT_AUTH_SIGNING_SECRET=oi2ho2ntl2nt2l3n2li
            - LMS_CONTACTS_KEY=AqZE4ijtNb2f21t3gmv_bXwKZUHB6H8v75qKcbxrOe0=
            - LMS_CONTACTS_KEY_ROTATE1=4OpiE_bfMlewpzKsCik7AmYeaNgJJ6pXVHwbdLbEgco=
            - LMS_CONTACTS_KEY_ROTATE2=AqZE4ijtNb2f21t3gmv_bXwKZUHB6H8v75qKcbxrOe0=
            - YENOT_DEBUG=debug
            - YENOT_2FA_DIR=/temp2fa
        volumes:
            - ./yenot:/lms/yenot
            - ./yenot-auth:/lms/yenot-auth
            - ./yenot-html:/lms/yenot-html
            - ./temp2fa:/temp2fa
    db:
        build: postgresql
        image: pg-lms-demo
        environment:
            - POSTGRES_PASSWORD=abc123
    tests:
        build: tests
        image: lms-test-suite
        environment:
            - PYTHONUNBUFFERED=1
            - INIT_ADMIN_USER=admin
            - INIT_ADMIN_PASSWORD=zyx987
            - LMS_URL=http://web:8088
            - YENOT_2FA_DIR=/temp2fa
        volumes:
            - ./tests:/tests
            - ./temp2fa:/temp2fa
