-- create lms generic user roles
CREATE ROLE lmsadmin;
ALTER ROLE lmsadmin WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN PASSWORD 'very-secret-123';
CREATE ROLE lmsserver;
ALTER ROLE lmsserver WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN PASSWORD 'secret123';

