CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER DEFAULT PRIVILEGES FOR ROLE lmsadmin GRANT USAGE ON SCHEMAS TO lmsserver;
ALTER DEFAULT PRIVILEGES FOR ROLE lmsadmin GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO lmsserver;
ALTER DEFAULT PRIVILEGES FOR ROLE lmsadmin GRANT EXECUTE ON FUNCTIONS TO lmsserver;
ALTER DEFAULT PRIVILEGES FOR ROLE lmsadmin GRANT SELECT,UPDATE,USAGE ON SEQUENCES TO lmsserver;
